--PRODUCT TABLE

CREATE PROCEDURE FINAL_CDW_SAPP_PRODUCT
AS
BEGIN
DROP TABLE IF EXISTS LANDING.CDW_SAPP_PRODUCT
SELECT DISTINCT * INTO LANDING.CDW_SAPP_PRODUCT FROM SOURCEFILE.CDW_SAPP_PRODUCT;

ALTER TABLE LANDING.CDW_SAPP_PRODUCT
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_PRODUCT');

SELECT * FROM LANDING.CDW_SAPP_PRODUCT;

EXEC STAGING_CDW_SAPP_PRODUCT;
SELECT * FROM STAGING.CDW_SAPP_PRODUCT;

EXEC DW_CDW_SAPP_PRODUCT;
SELECT * FROM DW.CDW_SAPP_D_PRODUCT;
END

EXEC FINAL_CDW_SAPP_PRODUCT;




--BRANCH TABLE


CREATE PROCEDURE FINAL_CDW_SAPP_BRANCH
AS
BEGIN
DROP TABLE IF EXISTS LANDING.CDW_SAPP_BRANCH
SELECT DISTINCT * INTO LANDING.CDW_SAPP_BRANCH FROM SOURCEFILE.CDW_SAPP_BRANCH;

ALTER TABLE LANDING.CDW_SAPP_BRANCH
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_BRANCH');

SELECT * FROM LANDING.CDW_SAPP_BRANCH;

EXEC STAGING_CDW_SAPP_BRANCH;
SELECT * FROM STAGING.CDW_SAPP_BRANCH;

EXEC DW_CDW_SAPP_BRANCH;
SELECT * FROM DW.CDW_SAPP_D_BRANCH;

END

EXEC FINAL_CDW_SAPP_BRANCH;


--SUPPLIER TABLE

CREATE PROCEDURE FINAL_CDW_SAPP_SUPPLIER
AS
BEGIN
DROP TABLE IF EXISTS LANDING.CDW_SAPP_SUPPLIER
SELECT DISTINCT * INTO LANDING.CDW_SAPP_SUPPLIER FROM SOURCEFILE.CDW_SAPP_SUPPLIER;

ALTER TABLE LANDING.CDW_SAPP_SUPPLIER
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_SUPPLIER');

SELECT * FROM LANDING.CDW_SAPP_SUPPLIER;

EXEC STAGING_CDW_SAPP_SUPPLIER;
SELECT * FROM STAGING.CDW_SAPP_SUPPLIER;

EXEC DW_CDW_SAPP_SUPPLIER;	
SELECT * FROM DW.CDW_SAPP_D_SUPPLIER;
END

EXEC FINAL_CDW_SAPP_SUPPLIER;


--SALES TABLE

CREATE PROCEDURE FINAL_CDW_SAPP_SALES
AS
BEGIN
DROP TABLE IF EXISTS LANDING.CDW_SAPP_SALES
SELECT DISTINCT * INTO LANDING.CDW_SAPP_SALES FROM SOURCEFILE.CDW_SAPP_F_SALES_BR_4382;

ALTER TABLE LANDING.CDW_SAPP_SALES
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_SALES'),
SALES_ID INTEGER IDENTITY(100000001,1);

ALTER TABLE LANDING.CDW_SAPP_SALES
ADD SALES_DATE DATETIME;
UPDATE LANDING.CDW_SAPP_SALES SET SALES_DATE=CONCAT(CAST(day AS VARCHAR(255)), '-', CAST(month AS VARCHAR(255)), '-', CAST(year AS VARCHAR(255)));

ALTER TABLE LANDING.CDW_SAPP_SALES
ADD
ID INT IDENTITY(101, 1), 
Composite_ID AS (CONVERT(VARCHAR(20),DAY) + '' + Convert(VARCHAR(20),MONTH(CONVERT(NVARCHAR, [Month]) + '' + CONVERT(NVARCHAR, [Year]))) + '' + CONVERT(VARCHAR(20),Right(YEAR,2)) + '' + CONVERT(VARCHAR(20), ID))
 
SELECT  * FROM LANDING.CDW_SAPP_SALES;

EXEC STAGING_SALES_MERGE;
SELECT * FROM STAGING.CDW_SAPP_SALES;
	
EXEC DW_SALES_MERGE;	
SELECT * FROM DW.CDW_SAPP_F_SALES;
END

EXEC FINAL_CDW_SAPP_SALES;



--CUSTOMER TABLE

CREATE  PROCEDURE FINAL_CDW_SAPP_CUSTOMER
AS
BEGIN
Drop Table If Exists LANDING.CDW_SAPP_CUSTOMER
SELECT DISTINCT * INTO LANDING.CDW_SAPP_CUSTOMER FROM SOURCEFILE.CDW_SAPP_CUSTOMER_2;

ALTER TABLE LANDING.CDW_SAPP_CUSTOMER
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_CUSTOMER');


SELECT * FROM LANDING.CDW_SAPP_CUSTOMER;

EXEC STAGING_CDW_SAPP_CUSTOMER;
SELECT * FROM STAGING.CDW_SAPP_CUSTOMER;
EXEC CDW_D_CUSTOMER;	
SELECT * FROM DW.CDW_SAPP_D_CUSTOMER;
END


EXEC FINAL_CDW_SAPP_CUSTOMER


--TIME TABLE

CREATE  PROCEDURE FINAL_CDW_SAPP_TIME
AS
BEGIN

INSERT INTO LANDING.CDW_SAPP_D_CALENDAR (TIMEID,DAY, MONTH, QUARTER, YEAR)
SELECT
		TIMEID, 
		DATEPART(DAY, TIME_KEY) AS DAY,
		DATEPART(MONTH, TIME_KEY) AS MONTH,
		CONCAT('Q', DATEPART(QUARTER, TIME_KEY)) AS QUARTER,
		DATEPART(YEAR, TIME_KEY) AS YEAR
		FROM SOURCEFILE.CDW_SAPP_D_CALENDAR;
 
ALTER TABLE LANDING.CDW_SAPP_D_CALENDAR
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_D_CALENDAR');

SELECT * FROM LANDING.CDW_SAPP_D_CALENDAR;


EXEC STAGING_CDW_SAPP_TIME;
SELECT * FROM STAGING.CDW_SAPP_TIME;

EXEC DW_CDW_SAPP_SUPPLIER;	
SELECT * FROM DW.CDW_SAPP_D_TIME;
END

EXEC FINAL_CDW_SAPP_TIME;





        
	
	
	
	
	
	
