--CREAION OF LANDING TABLES AND LOADING OF DATA



--BRANCH TABLE
CREATE SCHEMA LANDING;

SELECT DISTINCT * INTO LANDING.CDW_SAPP_BRANCH FROM sourcefile.CDW_SAPP_BRANCH;

ALTER TABLE LANDING.CDW_SAPP_BRANCH
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_BRANCH');

UPDATE LANDING.CDW_SAPP_BRANCH SET BRANCH_ZIP=19335 WHERE BRANCH_CODE=4381;
UPDATE LANDING.CDW_SAPP_BRANCH SET BRANCH_PHONE=7296387594 WHERE BRANCH_CODE=4381;
UPDATE LANDING.CDW_SAPP_BRANCH SET BRANCH_NAME='SAPP_Downingtown' WHERE BRANCH_CODE=4381;

SELECT * FROM LANDING.CDW_SAPP_BRANCH;




--CUSTOMER TABLE

SELECT DISTINCT * INTO LANDING.CDW_SAPP_CUSTOMER FROM sourcefile.CDW_SAPP_CUSTOMER;

ALTER TABLE LANDING.CDW_SAPP_CUSTOMER
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_CUSTOMER');

SELECT * FROM LANDING.CDW_SAPP_CUSTOMER;



--PRODUCT TABLE

SELECT DISTINCT * INTO LANDING.CDW_SAPP_PRODUCT FROM sourcefile.CDW_SAPP_PRODUCT;

ALTER TABLE LANDING.CDW_SAPP_PRODUCT
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_PRODUCT');

SELECT * FROM LANDING.CDW_SAPP_PRODUCT;




--SALES TABLE

SELECT DISTINCT * INTO LANDING.CDW_SAPP_SALES FROM sourcefile.CDW_SAPP_F_SALES_BR_4382;

ALTER TABLE LANDING.CDW_SAPP_SALES
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_SALES'),
SALES_ID INTEGER IDENTITY(100000001,1);

ALTER TABLE LANDING.CDW_SAPP_SALES
ADD SALES_DATE DATETIME;
UPDATE LANDING.CDW_SAPP_SALES SET SALES_DATE=CONCAT(CAST(day AS VARCHAR(255)), '-', CAST(month AS VARCHAR(255)), '-', CAST(year AS VARCHAR(255)));

ALTER TABLE LANDING.CDW_SAPP_SALES
ADD
ID INT IDENTITY(101, 1), 
Composite_ID AS (CONVERT(VARCHAR(20),DAY) + '' + Convert(VARCHAR(20),MONTH(CONVERT(NVARCHAR, [Month]) + '' + CONVERT(NVARCHAR, [Year]))) + '' + CONVERT(VARCHAR(20),Right(YEAR,2)) + '' + CONVERT(VARCHAR(20), ID))
 
SELECT  * FROM LANDING.CDW_SAPP_SALES;




--CALENDER TABLE
CREATE TABLE LANDING.CDW_SAPP_D_CALENDAR (
	TIMEID VARCHAR(8) ,
	DAY INT,
    MONTH INT,
    QUARTER VARCHAR(8),
    YEAR INT
);
 
INSERT INTO LANDING.CDW_SAPP_D_CALENDAR (TIMEID,DAY, MONTH, QUARTER, YEAR)
SELECT
		TIMEID, 
		DATEPART(DAY, TIME_KEY) AS DAY,
		DATEPART(MONTH, TIME_KEY) AS MONTH,
		CONCAT('Q', DATEPART(QUARTER, TIME_KEY)) AS QUARTER,
		DATEPART(YEAR, TIME_KEY) AS YEAR
		FROM sourcefile.CDW_SAPP_D_CALENDAR;
 
ALTER TABLE LANDING.CDW_SAPP_D_CALENDAR
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_D_CALENDAR');

SELECT * FROM LANDING.CDW_SAPP_D_CALENDAR;




--SUPPLIER TABLE

SELECT DISTINCT * INTO LANDING.CDW_SAPP_SUPPLIER FROM sourcefile.CDW_SAPP_SUPPLIER;

ALTER TABLE LANDING.CDW_SAPP_SUPPLIER
ADD LOAD_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
SOURCE varchar(max) NOT NULL DEFAULT('CDW_SAPP_SUPPLIER');

SELECT * FROM LANDING.CDW_SAPP_SUPPLIER;
